{{ config(materialized="table") }}

select
    md5(concat_ws('|', 'entidades', apf)) as id_silver_frente,
    'Minha Casa Minha Vida'::text as programa,
    'Entidades'::text as frente_mcmv,
    'Subsidiada'::text as grupo_linha,
    'FDS / Entidades'::text as linha_mcmv,
    'empreendimento_apf'::text as grao_registro,
    'silver'::text as fonte_camada,
    'entidades_fds'::text as fonte_schema,
    'fds_empreendimento'::text as fonte_tabela,
    'raw.novo_mcmv_fds_* + int_059_caixa_pj'::text as fonte_minio_staging,
    apf::text as apf,
    apf::text as contrato,
    apf::text as codigo_empreendimento,
    empreendimento_nome::text as nome_empreendimento,
    cod_ibge::text as codigo_ibge_municipio,
    municipio::text as municipio,
    uf::text as uf,
    'Entidade Organizadora'::text as responsavel_tipo,
    eo_cnpj::text as responsavel_id,
    eo_nome::text as responsavel_nome,
    agente_financeiro::text as agente_financeiro,
    1::integer as quantidade_empreendimentos,
    1::integer as quantidade_contratos,
    quantidade_uh::integer as quantidade_uh,
    qt_uh_alienadas::integer as quantidade_uh_entregues,
    valor_contratado::numeric(15, 2) as valor_contratado,
    valor_desembolsado::numeric(15, 2) as valor_desembolsado,
    percentual_execucao_fisica::numeric(10, 2) as percentual_execucao_fisica,
    percentual_execucao_financeira::numeric(10, 2) as percentual_execucao_financeira,
    coalesce(situacao_gefus, fase_contrato)::text as status_operacional,
    null::date as dt_referencia,
    dt_contratacao::date as dt_contratacao,
    dt_inicio_obra::date as dt_inicio_obra,
    dt_previsao_entrega::date as dt_previsao_entrega,
    dt_entrega::date as dt_entrega,
    coalesce(dt_ultima_liberacao, dt_entrega, dt_previsao_entrega, dt_contratacao)::date as dt_ultima_atualizacao,
    'Entidades/FDS vem da silver existente entidades_fds.fds_empreendimento.'::text as observacao_silver,
    current_timestamp as dt_silver
from {{ ref("fds_empreendimento") }}
where apf is not null
