name: 'mcid'

version: 1.0.0
config-version: 2

profile: mcid

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  mcid:
    +database: cidades
    metadata:
      +materialized: incremental
      +schema: metadata
    empreendimento_far_dbt:
      +materialized: table
      +schema: empreendimento_far
      silver:
        +materialized: table
      gold:
        +materialized: table

    conjuntura_dbt:
      +materialized: table
      +schema: conjuntura
      bronze:
        +materialized: table
        +schema: conjuntura_bronze
      silver:
        +materialized: table
        +schema: conjuntura_silver
      gold:
        +materialized: table
        +schema: conjuntura_gold

on-run-start:
  - '{{create_udfs()}}'
