select 
    cast(data_referencia as date) as data_referencia,
    cast(cod_ibge as varchar(7)) as cod_ibge,
    cast(txt_municipio as varchar(200)) as txt_municipio,
    cast(txt_uf as varchar(2)) as txt_uf,
    cast(txt_regiao as varchar(50)) as txt_regiao,
    cast(data_assinatura_financiamento as timestamp) as data_assinatura_financiamento,
    cast(qtd_uh_financiadas as bigint) as qtd_uh_financiadas,
    {{ parse_financial_value('vlr_financiamento') }} as vlr_financiamento,
    {{ parse_financial_value('vlr_subsidio_desconto_fgts') }} as vlr_subsidio_desconto_fgts,
    {{ parse_financial_value('vlr_subsidio_desconto_ogu') }} as vlr_subsidio_desconto_ogu,
    {{ parse_financial_value('vlr_subsidio_equilibrio_fgts') }} as vlr_subsidio_equilibrio_fgts,
    {{ parse_financial_value('vlr_subsidio_equilibrio_ogu') }} as vlr_subsidio_equilibrio_ogu,
    {{ parse_financial_value('vlr_compra') }} as vlr_compra,
    {{ parse_financial_value('vlr_renda_familiar') }} as vlr_renda_familiar,
    {{ parse_financial_value('num_taxa_juros') }} as num_taxa_juros,
    cast(txt_programa_fgts as varchar(150)) as txt_programa_fgts,
    cast(txt_tipo_imovel as varchar(50)) as txt_tipo_imovel,
    cast(bln_cotista as varchar(10)) as bln_cotista,
    cast(txt_sistema_amortizacao as varchar(10)) as txt_sistema_amortizacao,
    cast(nullif(nullif(dte_nascimento, ''), 'NaN') as date) as dte_nascimento,
    cast(txt_compatibilidade_faixa_renda as varchar(50)) as txt_compatibilidade_faixa_renda,
    cast(txt_nome_empreendimento as varchar) as txt_nome_empreendimento,
    cast(co_sexo as varchar(1)) as co_sexo,
    cast(dt_ingest as timestamp) as dt_ingest,
    cast(arquivo_origem as varchar) as arquivo_origem
from {{ source('dados_abertos_cidades', 'mcmv_fgts_analitico') }}
