version: 2

sources:
  - name: infomoney
    schema: infomoney
    tables:
      - name: acoes_imob

  - name: dados_abertos_cidades
    schema: dados_abertos_cidades
    tables:
      - name: mcmv_fgts_analitico
      - name: dados_abertos_snhis_regularidade_entes
      - name: dados_abertos_pbqp_h_simac
      - name: dados_abertos_pbqp_h_siac
  
  - name: novo_caged
    schema: novo_caged
    tables:
      - name: saldo_estoque_construcao_edificios

  - name: __dados_brutos
    schema: __dados_brutos
    tables:
      - name: novo_mcmv_far_consolidado
      - name: novo_mcmv_far_financeiro_mensal
      - name: int_empreendimentos_int040_far_caixa_pj
      - name: int_empreendimentos_int_054_far_bb_pj
      - name: dados_prioritarios_disponibilizados_snh_empreendimentos
      - name: dados_abertos_mcmv_ogu_empreendimentos
      - name: dados_prioritarios_recebidos_bb_empreendimentos
      - name: dados_prioritarios_recebidos_caixa_empreendimentos
      - name: novos_dados_mcmv_far
      - name: novo_mcmv_far_contratacao
      - name: novo_mcmv_far_obra_mensal
