{{ config(materialized="table") }}

select
    md5(concat_ws('|', 'far', apf)) as id_silver_frente,
    'Minha Casa Minha Vida'::text as programa,
    'FAR'::text as frente_mcmv,
    'Subsidiada'::text as grupo_linha,
    'FAR'::text as linha_mcmv,
    'empreendimento_apf'::text as grao_registro,
    'silver'::text as fonte_camada,
    'empreendimento_far'::text as fonte_schema,
    'empreendimento'::text as fonte_tabela,
    'raw.novo_mcmv_far_* + dados_prioritarios_recebidos_caixa'::text as fonte_minio_staging,
    apf::text as apf,
    apf::text as contrato,
    apf::text as codigo_empreendimento,
    empreendimento_nome::text as nome_empreendimento,
    null::text as codigo_ibge_municipio,
    municipio::text as municipio,
    uf::text as uf,
    'Proponente/Tomador'::text as responsavel_tipo,
    coalesce(proponente_cnpj, tomador_cnpj)::text as responsavel_id,
    coalesce(proponente_nome, tomador_nome)::text as responsavel_nome,
    agente_financeiro::text as agente_financeiro,
    1::integer as quantidade_empreendimentos,
    1::integer as quantidade_contratos,
    quantidade_uh::integer as quantidade_uh,
    case when dt_entrega is not null then quantidade_uh::integer end as quantidade_uh_entregues,
    valor_contratado::numeric(15, 2) as valor_contratado,
    valor_desembolsado::numeric(15, 2) as valor_desembolsado,
    percentual_execucao_fisica::numeric(10, 2) as percentual_execucao_fisica,
    percentual_execucao_financeira::numeric(10, 2) as percentual_execucao_financeira,
    situacao_empreendimento::text as status_operacional,
    null::date as dt_referencia,
    dt_contratacao::date as dt_contratacao,
    null::date as dt_inicio_obra,
    dt_previsao_entrega::date as dt_previsao_entrega,
    dt_entrega::date as dt_entrega,
    coalesce(dt_entrega, dt_conclusao_obra, dt_previsao_entrega, dt_contratacao)::date as dt_ultima_atualizacao,
    'FAR vem da silver existente empreendimento_far.empreendimento.'::text as observacao_silver,
    current_timestamp as dt_silver
from {{ ref("empreendimento") }}
where apf is not null
