{{ config(materialized="table") }}

select
    md5(concat_ws('|', 'conjuntura-fgts', ano::text, mes::text)) as id_silver_frente,
    'Minha Casa Minha Vida'::text as programa,
    'Conjuntura'::text as frente_mcmv,
    'Contexto'::text as grupo_linha,
    'FGTS financiamentos habitacionais'::text as linha_mcmv,
    'indicador_macro_mensal'::text as grao_registro,
    'silver'::text as fonte_camada,
    'conjuntura_silver'::text as fonte_schema,
    'silver_fgts_financiamentos_habitacionais'::text as fonte_tabela,
    'conjuntura_bronze.bronze_fgts_financiamentos_habitacionais'::text as fonte_minio_staging,
    null::text as apf,
    null::text as contrato,
    null::text as codigo_empreendimento,
    null::text as nome_empreendimento,
    null::text as codigo_ibge_municipio,
    null::text as municipio,
    null::text as uf,
    'Indicador setorial'::text as responsavel_tipo,
    null::text as responsavel_id,
    'FGTS habitacional'::text as responsavel_nome,
    null::text as agente_financeiro,
    null::integer as quantidade_empreendimentos,
    null::integer as quantidade_contratos,
    financiamento_pf_uh_total_geral::integer as quantidade_uh,
    null::integer as quantidade_uh_entregues,
    financiamento_pf_valor_total_geral::numeric(15, 2) as valor_contratado,
    null::numeric(15, 2) as valor_desembolsado,
    null::numeric(10, 2) as percentual_execucao_fisica,
    null::numeric(10, 2) as percentual_execucao_financeira,
    'Indicador mensal FGTS'::text as status_operacional,
    make_date(ano::integer, mes::integer, 1) as dt_referencia,
    null::date as dt_contratacao,
    null::date as dt_inicio_obra,
    null::date as dt_previsao_entrega,
    null::date as dt_entrega,
    make_date(ano::integer, mes::integer, 1) as dt_ultima_atualizacao,
    'Conjuntura nao tem APF/empreendimento; serve para calibrar alertas e metas do relogio.'::text as observacao_silver,
    current_timestamp as dt_silver
from {{ ref("silver_fgts_financiamentos_habitacionais") }}
where ano is not null
  and mes is not null
