{{ config(materialized="table") }}

select
    md5(concat_ws('|', 'mcmv-cidades', nu_contrato, dt_referencia, valor)) as id_silver_frente,
    'Minha Casa Minha Vida'::text as programa,
    'MCMV Cidades'::text as frente_mcmv,
    'Subsidiada'::text as grupo_linha,
    coalesce(no_programa, 'MCMV Cidades')::text as linha_mcmv,
    'contrato_ente_publico'::text as grao_registro,
    'sftp'::text as fonte_camada,
    'sftp'::text as fonte_schema,
    'pmcmv_cidades_mcid_2026_03_01'::text as fonte_tabela,
    'GEFUS/pmcmv_cidades'::text as fonte_minio_staging,
    null::text as apf,
    nu_contrato::text as contrato,
    nu_contrato::text as codigo_empreendimento,
    no_programa::text as nome_empreendimento,
    nu_ibge::text as codigo_ibge_municipio,
    no_municipio::text as municipio,
    sg_uf::text as uf,
    'Ente Publico'::text as responsavel_tipo,
    null::text as responsavel_id,
    no_ente_publico::text as responsavel_nome,
    null::text as agente_financeiro,
    null::integer as quantidade_empreendimentos,
    1::integer as quantidade_contratos,
    null::integer as quantidade_uh,
    null::integer as quantidade_uh_entregues,
    {{ parse_financial_value('valor') }} as valor_contratado,
    null::numeric(15, 2) as valor_desembolsado,
    null::numeric(10, 2) as percentual_execucao_fisica,
    null::numeric(10, 2) as percentual_execucao_financeira,
    'Contratado/Lancado'::text as status_operacional,
    {{ target.schema }}.parse_date_br(dt_referencia) as dt_referencia,
    {{ target.schema }}.parse_date_br(dt_contratacao) as dt_contratacao,
    null::date as dt_inicio_obra,
    null::date as dt_previsao_entrega,
    null::date as dt_entrega,
    coalesce({{ target.schema }}.parse_date_br(dt_posicao), {{ target.schema }}.parse_date_br(dt_remessa), {{ target.schema }}.parse_date_br(dt_referencia)) as dt_ultima_atualizacao,
    'MCMV Cidades tem grão de contrato/ente publico; sem APF na fonte atual.'::text as observacao_silver,
    current_timestamp as dt_silver
from {{ source("sftp_mcmv", "pmcmv_cidades_mcid_2026_03_01") }}
where nullif(trim(nu_contrato), '') is not null
