{% macro mcmv_silver_empty_contract(frente_mcmv, grupo_linha, linha_mcmv, observacao_silver) %}
select
    null::text as id_silver_frente,
    'Minha Casa Minha Vida'::text as programa,
    '{{ frente_mcmv }}'::text as frente_mcmv,
    '{{ grupo_linha }}'::text as grupo_linha,
    '{{ linha_mcmv }}'::text as linha_mcmv,
    'fonte_nao_carregada'::text as grao_registro,
    'lacuna'::text as fonte_camada,
    null::text as fonte_schema,
    null::text as fonte_tabela,
    null::text as fonte_minio_staging,
    null::text as apf,
    null::text as contrato,
    null::text as codigo_empreendimento,
    null::text as nome_empreendimento,
    null::text as codigo_ibge_municipio,
    null::text as municipio,
    null::text as uf,
    null::text as responsavel_tipo,
    null::text as responsavel_id,
    null::text as responsavel_nome,
    null::text as agente_financeiro,
    null::integer as quantidade_empreendimentos,
    null::integer as quantidade_contratos,
    null::integer as quantidade_uh,
    null::integer as quantidade_uh_entregues,
    null::numeric(15, 2) as valor_contratado,
    null::numeric(15, 2) as valor_desembolsado,
    null::numeric(10, 2) as percentual_execucao_fisica,
    null::numeric(10, 2) as percentual_execucao_financeira,
    'Fonte ainda nao localizada no schema sftp'::text as status_operacional,
    null::date as dt_referencia,
    null::date as dt_contratacao,
    null::date as dt_inicio_obra,
    null::date as dt_previsao_entrega,
    null::date as dt_entrega,
    null::date as dt_ultima_atualizacao,
    '{{ observacao_silver }}'::text as observacao_silver,
    current_timestamp as dt_silver
where false
{% endmacro %}
